name: Code Quality

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    name: Check code
    env:
      PHP_VERSION: 7.4.5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ PHP_VERSION }}
          extensions: mbstring, intl
          tools: composer

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-${{ PHP_VERSION }}-${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: php-${{ PHP_VERSION }}-${{ runner.os }}-composer

      - name: Install dependencies
        run: composer install --no-progress

      - name: Run PHPStan
        run: composer run-script phpstan
